/* =========================================================================
   IDLE QUEST — 02 AUDIO
   A full procedural score engine: seeded motif-based composition, layered
   orchestral synthesis, adaptive state crossfades, and synthesized SFX.
   No samples, no downloads — everything is generated by WebAudio.
   ========================================================================= */

const A = {
  ctx: null, ok: false, ready: false,
  master: null, musicBus: null, sfxBus: null, revIn: null, comp: null,
  volMusic: 0.72, volSfx: 0.82, muted: false,
  noiseBuf: null, seed: 1,
  // scheduler
  bpm: 84, beat: 0, bar: 0, nextTime: 0, timer: null,
  score: null, nextScore: null, state: '', pending: '',
  intensity: 0.5, targetIntensity: 0.5,
  motif: null, motifBar: 0, sect: 0,
  lastSfx: {},
};

/* ------------------------------ THEORY ------------------------------ */
const MODES = {
  aeolian: [0, 2, 3, 5, 7, 8, 10],
  dorian: [0, 2, 3, 5, 7, 9, 10],
  ionian: [0, 2, 4, 5, 7, 9, 11],
  mixo: [0, 2, 4, 5, 7, 9, 10],
  phrygian: [0, 1, 3, 5, 7, 8, 10],
  lydian: [0, 2, 4, 6, 7, 9, 11],
  harmMin: [0, 2, 3, 5, 7, 8, 11],
};
/** midi -> hz */
const hz = m => 440 * Math.pow(2, (m - 69) / 12);
/** scale degree (can exceed octave, can be negative) -> midi offset */
function degToSemi(mode, d) {
  const sc = MODES[mode], n = sc.length;
  const oct = Math.floor(d / n), i = ((d % n) + n) % n;
  return sc[i] + oct * 12;
}
/** build a triad/seventh from a scale degree */
function chordNotes(mode, root, deg, seventh, oct) {
  const o = (oct || 0) * 12;
  const a = [degToSemi(mode, deg), degToSemi(mode, deg + 2), degToSemi(mode, deg + 4)];
  if (seventh) a.push(degToSemi(mode, deg + 6));
  return a.map(s => root + s + o);
}

/* ------------------------------ SCORES ------------------------------ */
/* Each score: tempo, mode, chord progression (scale degrees), layer flags,
   and an intensity floor. The composer fills in motifs at runtime.        */
function buildScores(rootMidi) {
  const R = rootMidi;
  return {
    menu: {
      bpm: 62, mode: 'aeolian', root: R, prog: [0, 5, 3, 4], bars: 4, sevenths: true,
      lay: { pad: 1, choir: .85, harp: .8, strings: .5, flute: .55, bass: .5, drums: 0, taiko: 0, bell: .5 }, swing: .06, base: .2
    },
    explore: {
      bpm: 78, mode: 'aeolian', root: R, prog: [0, 5, 6, 3, 0, 5, 3, 4], bars: 8, sevenths: true,
      lay: { pad: .95, choir: .42, harp: .72, strings: .8, flute: .62, bass: .72, drums: .3, taiko: .2, horn: .5 }, swing: .04, base: .3
    },
    wilds: {
      bpm: 88, mode: 'dorian', root: R, prog: [0, 3, 6, 4, 0, 3, 1, 4], bars: 8, sevenths: true,
      lay: { pad: .8, choir: .3, harp: .5, strings: .85, flute: .5, bass: .8, drums: .5, taiko: .38, horn: .62 }, swing: .03, base: .38
    },
    town: {
      bpm: 96, mode: 'ionian', root: R + 5, prog: [0, 4, 5, 3, 0, 4, 1, 4], bars: 8, sevenths: false,
      lay: { pad: .55, choir: .12, harp: .95, strings: .55, flute: .9, bass: .6, drums: .28, taiko: 0, bell: .4 }, swing: .12, base: .3
    },
    combat: {
      bpm: 132, mode: 'phrygian', root: R, prog: [0, 0, 1, 0, 0, 6, 1, 4], bars: 8, sevenths: false,
      lay: { pad: .4, choir: .3, strings: .95, bass: .95, drums: .95, taiko: .8, brass: .8, ost: 1 }, swing: 0, base: .62
    },
    boss: {
      bpm: 146, mode: 'harmMin', root: R - 2, prog: [0, 0, 5, 6, 0, 0, 4, 4], bars: 8, sevenths: true,
      lay: { pad: .5, choir: .95, strings: 1, bass: 1, drums: 1, taiko: 1, brass: 1, ost: 1, bell: .3 }, swing: 0, base: .82
    },
    raid: {
      bpm: 120, mode: 'harmMin', root: R - 4, prog: [0, 6, 5, 0, 3, 6, 4, 4], bars: 8, sevenths: true,
      lay: { pad: .7, choir: 1, strings: 1, bass: .95, drums: .9, taiko: .95, brass: .9, ost: .8 }, swing: 0, base: .78
    },
    victory: {
      bpm: 104, mode: 'ionian', root: R + 5, prog: [0, 4, 5, 4, 0, 3, 4, 0], bars: 8, sevenths: false,
      lay: { pad: .8, choir: .8, harp: .7, strings: 1, flute: .6, bass: .8, drums: .7, taiko: .6, brass: 1, bell: .8 }, swing: 0, base: .8
    },
    night: {
      bpm: 66, mode: 'aeolian', root: R - 5, prog: [0, 3, 5, 4], bars: 4, sevenths: true,
      lay: { pad: 1, choir: .6, harp: .55, strings: .45, flute: .4, bass: .5, drums: 0, bell: .55 }, swing: .05, base: .2
    },
  };
}

/* ------------------------------ INIT ------------------------------ */
function audioInit(seed) {
  if (A.ctx) return true;
  try {
    const AC = window.AudioContext || window.webkitAudioContext;
    if (!AC) return false;
    A.ctx = new AC({ latencyHint: 'interactive' });
  } catch (e) { return false; }
  const c = A.ctx;
  A.seed = seed || 1;

  A.comp = c.createDynamicsCompressor();
  A.comp.threshold.value = -14; A.comp.knee.value = 26; A.comp.ratio.value = 3.2;
  A.comp.attack.value = 0.006; A.comp.release.value = 0.26;

  A.master = c.createGain(); A.master.gain.value = 0.9;
  A.master.connect(A.comp); A.comp.connect(c.destination);

  A.musicBus = c.createGain(); A.musicBus.gain.value = A.volMusic;
  A.sfxBus = c.createGain(); A.sfxBus.gain.value = A.volSfx;
  A.musicBus.connect(A.master); A.sfxBus.connect(A.master);

  // ---- reverb (generated impulse response: exponential-decay noise) ----
  const rev = c.createConvolver();
  const len = Math.floor(c.sampleRate * 2.9);
  const ir = c.createBuffer(2, len, c.sampleRate);
  const rr = new RNG(A.seed ^ 0x5eed);
  for (let ch = 0; ch < 2; ch++) {
    const d = ir.getChannelData(ch);
    for (let i = 0; i < len; i++) {
      const t = i / len;
      // early reflections + smooth tail
      const env = Math.pow(1 - t, 2.6) * (1 - Math.exp(-i / (c.sampleRate * 0.012)));
      d[i] = (rr.f() * 2 - 1) * env;
    }
  }
  rev.buffer = ir;
  A.revIn = c.createGain(); A.revIn.gain.value = 1;
  const revOut = c.createGain(); revOut.gain.value = 0.5;
  const revLP = c.createBiquadFilter(); revLP.type = 'lowpass'; revLP.frequency.value = 4200;
  A.revIn.connect(rev); rev.connect(revLP); revLP.connect(revOut); revOut.connect(A.master);

  // ---- shared noise buffer ----
  const nlen = Math.floor(c.sampleRate * 2);
  A.noiseBuf = c.createBuffer(1, nlen, c.sampleRate);
  const nd = A.noiseBuf.getChannelData(0);
  for (let i = 0; i < nlen; i++) nd[i] = rr.f() * 2 - 1;

  A.scores = buildScores(new RNG(A.seed).ri(52, 59)); // root between E3 and G3
  A.ok = true;
  return true;
}
function audioResume() {
  if (!A.ctx) return;
  if (A.ctx.state === 'suspended') A.ctx.resume();
}
function audioSetVol(m, s) {
  A.volMusic = m; A.volSfx = s;
  if (A.musicBus) A.musicBus.gain.setTargetAtTime(A.muted ? 0 : m, A.ctx.currentTime, .05);
  if (A.sfxBus) A.sfxBus.gain.setTargetAtTime(A.muted ? 0 : s, A.ctx.currentTime, .05);
}

/* ------------------------------ VOICES ------------------------------ */
function env(g, t, a, d, s, r, dur, peak) {
  const p = peak == null ? 1 : peak;
  g.gain.cancelScheduledValues(t);
  g.gain.setValueAtTime(0.0001, t);
  g.gain.exponentialRampToValueAtTime(Math.max(0.0002, p), t + a);
  g.gain.exponentialRampToValueAtTime(Math.max(0.0002, p * s), t + a + d);
  g.gain.setValueAtTime(Math.max(0.0002, p * s), t + Math.max(a + d, dur));
  g.gain.exponentialRampToValueAtTime(0.0001, t + Math.max(a + d, dur) + r);
}
/** Filters throw console warnings (and behave oddly) above Nyquist. */
function fq(f) { const n = (A.ctx ? A.ctx.sampleRate : 44100) * 0.5 - 200; return f < 20 ? 20 : f > n ? n : f; }
function osc(type, f, t, detune) {
  const o = A.ctx.createOscillator(); o.type = type; o.frequency.setValueAtTime(f, t);
  if (detune) o.detune.setValueAtTime(detune, t);
  return o;
}
function noiseSrc(t) { const n = A.ctx.createBufferSource(); n.buffer = A.noiseBuf; n.loop = true; return n; }
function sendRev(node, amt) { const g = A.ctx.createGain(); g.gain.value = amt; node.connect(g); g.connect(A.revIn); }

/* Warm sustaining pad — the harmonic bed. */
function vPad(t, f, d, gain, dest) {
  const c = A.ctx, g = c.createGain(), lp = c.createBiquadFilter();
  lp.type = 'lowpass'; lp.frequency.setValueAtTime(420, t);
  lp.frequency.linearRampToValueAtTime(1350, t + d * .55);
  lp.frequency.linearRampToValueAtTime(600, t + d + .8);
  lp.Q.value = .7;
  const dets = [-9, -3, 4, 11];
  for (let i = 0; i < dets.length; i++) {
    const o = osc(i & 1 ? 'sawtooth' : 'triangle', f * (i === 3 ? 2 : 1), t, dets[i]);
    o.connect(lp); o.start(t); o.stop(t + d + 1.1);
  }
  env(g, t, .9, .5, .78, .9, d, gain);
  lp.connect(g); g.connect(dest); sendRev(g, .55);
}
/* String ensemble — sawtooth stack, bow-like attack, gentle vibrato. */
function vStrings(t, f, d, gain, dest) {
  const c = A.ctx, g = c.createGain(), lp = c.createBiquadFilter();
  lp.type = 'lowpass'; lp.frequency.setValueAtTime(fq(1900 + gain * 2400), t); lp.Q.value = .5;
  const vib = osc('sine', 5.1, t); const vg = c.createGain(); vg.gain.value = f * .006;
  vib.connect(vg); vib.start(t); vib.stop(t + d + .6);
  for (const dt of [-7, 0, 6, 12]) {
    const o = osc('sawtooth', f, t, dt); vg.connect(o.frequency);
    o.connect(lp); o.start(t); o.stop(t + d + .5);
  }
  env(g, t, .16, .22, .82, .38, d, gain);
  lp.connect(g); g.connect(dest); sendRev(g, .38);
}
/* Brass — bright, punchy, filter sweep on attack. */
function vBrass(t, f, d, gain, dest) {
  const c = A.ctx, g = c.createGain(), lp = c.createBiquadFilter();
  lp.type = 'lowpass'; lp.Q.value = 3.2;
  lp.frequency.setValueAtTime(500, t);
  lp.frequency.exponentialRampToValueAtTime(fq(Math.min(7000, f * 9 + 900)), t + .07);
  lp.frequency.exponentialRampToValueAtTime(fq(Math.max(600, f * 3.4)), t + d * .8 + .05);
  for (const dt of [-5, 3]) { const o = osc('sawtooth', f, t, dt); o.connect(lp); o.start(t); o.stop(t + d + .3); }
  const sq = osc('square', f * .5, t); const sg = c.createGain(); sg.gain.value = .22; sq.connect(sg); sg.connect(lp); sq.start(t); sq.stop(t + d + .3);
  env(g, t, .035, .16, .72, .26, d, gain);
  lp.connect(g); g.connect(dest); sendRev(g, .3);
}
/* Horn calls — softer brass, long. */
function vHorn(t, f, d, gain, dest) {
  const c = A.ctx, g = c.createGain(), lp = c.createBiquadFilter();
  lp.type = 'lowpass'; lp.frequency.setValueAtTime(700, t);
  lp.frequency.linearRampToValueAtTime(2100, t + .16); lp.Q.value = 1.6;
  for (const dt of [-4, 5]) { const o = osc('sawtooth', f, t, dt); o.connect(lp); o.start(t); o.stop(t + d + .5); }
  const tri = osc('triangle', f * 2, t); const tg = c.createGain(); tg.gain.value = .18; tri.connect(tg); tg.connect(lp); tri.start(t); tri.stop(t + d + .5);
  env(g, t, .13, .3, .68, .55, d, gain);
  lp.connect(g); g.connect(dest); sendRev(g, .5);
}
/* Choir — stacked sines through formant band-passes + breath. */
function vChoir(t, f, d, gain, dest) {
  const c = A.ctx, g = c.createGain(), mixv = c.createGain(); mixv.gain.value = .34;
  const F = [[730, 1090, 2440], [400, 1700, 2300], [640, 1200, 2400]];
  const set = F[(Math.abs(Math.round(f)) % F.length)];
  for (const ff of set) {
    const bp = c.createBiquadFilter(); bp.type = 'bandpass'; bp.frequency.value = fq(ff); bp.Q.value = 7;
    for (const h of [1, 2, 3, 4]) {
      const o = osc(h === 1 ? 'sine' : 'sawtooth', f * h, t, (h - 1) * 4);
      const hg = c.createGain(); hg.gain.value = 1 / (h * h);
      o.connect(hg); hg.connect(bp); o.start(t); o.stop(t + d + .9);
    }
    bp.connect(mixv);
  }
  const n = noiseSrc(t); const nb = c.createBiquadFilter(); nb.type = 'bandpass'; nb.frequency.value = 2400; nb.Q.value = 1.2;
  const ng = c.createGain(); ng.gain.value = .012; n.connect(nb); nb.connect(ng); ng.connect(mixv); n.start(t); n.stop(t + d + .9);
  const vib = osc('sine', 4.4, t); const vg = c.createGain(); vg.gain.value = f * .009; vib.connect(vg); vib.start(t); vib.stop(t + d + .9);
  env(g, t, .5, .4, .8, .95, d, gain);
  mixv.connect(g); g.connect(dest); sendRev(g, .85);
}
/* Harp / plucked strings. */
function vHarp(t, f, d, gain, dest) {
  const c = A.ctx, g = c.createGain();
  const o = osc('triangle', f, t), o2 = osc('sine', f * 2.01, t);
  const g2 = c.createGain(); g2.gain.value = .3;
  const lp = c.createBiquadFilter(); lp.type = 'lowpass'; lp.frequency.setValueAtTime(fq(f * 7 + 1400), t);
  lp.frequency.exponentialRampToValueAtTime(fq(Math.max(300, f * 2)), t + d);
  o.connect(lp); o2.connect(g2); g2.connect(lp);
  o.start(t); o2.start(t); o.stop(t + d + .4); o2.stop(t + d + .4);
  g.gain.setValueAtTime(0.0001, t);
  g.gain.exponentialRampToValueAtTime(gain, t + .006);
  g.gain.exponentialRampToValueAtTime(0.0001, t + d + .35);
  lp.connect(g); g.connect(dest); sendRev(g, .45);
}
/* Flute / whistle lead. */
function vFlute(t, f, d, gain, dest) {
  const c = A.ctx, g = c.createGain(), mixv = c.createGain();
  const o = osc('sine', f, t); const o2 = osc('triangle', f, t, 6);
  const g2 = c.createGain(); g2.gain.value = .22;
  const vib = osc('sine', 5.6, t); const vg = c.createGain(); vg.gain.value = f * .008;
  vib.connect(vg); vg.connect(o.frequency); vg.connect(o2.frequency); vib.start(t); vib.stop(t + d + .3);
  o.connect(mixv); o2.connect(g2); g2.connect(mixv);
  const n = noiseSrc(t); const nb = c.createBiquadFilter(); nb.type = 'bandpass'; nb.frequency.value = fq(f * 2.2); nb.Q.value = 4;
  const ng = c.createGain(); ng.gain.value = .03; n.connect(nb); nb.connect(ng); ng.connect(mixv); n.start(t); n.stop(t + d + .2);
  o.start(t); o2.start(t); o.stop(t + d + .3); o2.stop(t + d + .3);
  env(g, t, .07, .12, .85, .2, d, gain);
  mixv.connect(g); g.connect(dest); sendRev(g, .42);
}
/* Bass — sub sine + saw body. */
function vBass(t, f, d, gain, dest) {
  const c = A.ctx, g = c.createGain(), lp = c.createBiquadFilter();
  lp.type = 'lowpass'; lp.frequency.setValueAtTime(260, t); lp.Q.value = 1.1;
  const o = osc('sine', f, t); const o2 = osc('sawtooth', f, t, 5); const g2 = c.createGain(); g2.gain.value = .35;
  o.connect(lp); o2.connect(g2); g2.connect(lp);
  o.start(t); o2.start(t); o.stop(t + d + .2); o2.stop(t + d + .2);
  env(g, t, .012, .1, .8, .14, d, gain);
  lp.connect(g); g.connect(dest); sendRev(g, .12);
}
/* Bell / celesta — 2-op FM. */
function vBell(t, f, d, gain, dest) {
  const c = A.ctx, g = c.createGain();
  const car = osc('sine', f, t);
  const mod = osc('sine', f * 2.76, t); const mg = c.createGain(); mg.gain.setValueAtTime(f * 2.4, t);
  mg.gain.exponentialRampToValueAtTime(f * .05, t + d * .6 + .1);
  mod.connect(mg); mg.connect(car.frequency);
  mod.start(t); car.start(t); mod.stop(t + d + .8); car.stop(t + d + .8);
  g.gain.setValueAtTime(0.0001, t);
  g.gain.exponentialRampToValueAtTime(gain, t + .004);
  g.gain.exponentialRampToValueAtTime(0.0001, t + d + .7);
  car.connect(g); g.connect(dest); sendRev(g, .7);
}
/* Percussion */
function vKick(t, gain, dest) {
  const c = A.ctx, g = c.createGain(), o = osc('sine', 150, t);
  o.frequency.exponentialRampToValueAtTime(42, t + .11);
  g.gain.setValueAtTime(gain, t); g.gain.exponentialRampToValueAtTime(.0001, t + .34);
  o.connect(g); g.connect(dest); o.start(t); o.stop(t + .36);
}
function vTaiko(t, gain, dest) {
  const c = A.ctx, g = c.createGain(), o = osc('sine', 108, t);
  o.frequency.exponentialRampToValueAtTime(58, t + .18);
  const n = noiseSrc(t); const nf = c.createBiquadFilter(); nf.type = 'bandpass'; nf.frequency.value = 240; nf.Q.value = .8;
  const ng = c.createGain(); ng.gain.setValueAtTime(gain * .5, t); ng.gain.exponentialRampToValueAtTime(.0001, t + .2);
  n.connect(nf); nf.connect(ng); ng.connect(dest); n.start(t); n.stop(t + .25);
  g.gain.setValueAtTime(gain, t); g.gain.exponentialRampToValueAtTime(.0001, t + .5);
  o.connect(g); g.connect(dest); o.start(t); o.stop(t + .52); sendRev(g, .28);
}
function vSnare(t, gain, dest) {
  const c = A.ctx, n = noiseSrc(t), hp = c.createBiquadFilter(); hp.type = 'highpass'; hp.frequency.value = 1500;
  const g = c.createGain(); g.gain.setValueAtTime(gain, t); g.gain.exponentialRampToValueAtTime(.0001, t + .16);
  n.connect(hp); hp.connect(g); g.connect(dest); n.start(t); n.stop(t + .18); sendRev(g, .3);
}
function vHat(t, gain, dest, open) {
  const c = A.ctx, n = noiseSrc(t), hp = c.createBiquadFilter(); hp.type = 'highpass'; hp.frequency.value = 7000;
  const g = c.createGain(); const d = open ? .28 : .05;
  g.gain.setValueAtTime(gain, t); g.gain.exponentialRampToValueAtTime(.0001, t + d);
  n.connect(hp); hp.connect(g); g.connect(dest); n.start(t); n.stop(t + d + .02);
}
function vCymbal(t, gain, dest) {
  const c = A.ctx, n = noiseSrc(t), hp = c.createBiquadFilter(); hp.type = 'highpass'; hp.frequency.value = 4200;
  const g = c.createGain(); g.gain.setValueAtTime(gain, t); g.gain.exponentialRampToValueAtTime(.0001, t + 1.5);
  n.connect(hp); hp.connect(g); g.connect(dest); n.start(t); n.stop(t + 1.6); sendRev(g, .8);
}

/* ------------------------------ COMPOSER ------------------------------ */
/* A motif is a list of {d: scaleDegree offset, t: 8th-note position, l: length}.
   Sections re-use and transform the motif so the music has memory & shape.   */
function makeMotif(rng, len, dense) {
  const m = []; let pos = 0, d = rng.pick([0, 2, 4, 4, 2, 7]);
  const rhy = dense ? [1, 1, 2, 1, 2, 1, 1, 3] : [2, 2, 3, 1, 4, 2, 3, 2];
  while (pos < len) {
    const l = rng.pick(rhy);
    if (rng.chance(dense ? .1 : .22)) { pos += l; continue; }         // rests give phrasing
    m.push({ d, t: pos, l: Math.min(l, len - pos) });
    const step = rng.wpick([-4, -2, -1, 1, 2, 3, 4, 0], [1, 3, 5, 5, 4, 2, 1, 1]);
    d = clamp(d + step, -3, 11);
    pos += l;
  }
  return m;
}
function transformMotif(m, rng, variant) {
  if (variant === 0) return m;
  return m.map(n => {
    const o = { d: n.d, t: n.t, l: n.l };
    if (variant === 1) o.d += 2;                       // transpose up a third
    else if (variant === 2) o.d = 7 - o.d;             // inversion around 5th
    else if (variant === 3) { o.d -= 2; o.l = Math.max(1, o.l - 1); }
    return o;
  });
}
function newSection(score) {
  const rng = new RNG((A.seed * 2654435761 + A.sect * 40503 + score.bpm) | 0);
  A.motif = makeMotif(rng, 16, score.bpm > 118);
  A.motifRng = rng;
}

/* ------------------------------ SCHEDULER ------------------------------ */
const SPB = () => 60 / A.bpm;      // seconds per beat (quarter)
const S8 = () => 30 / A.bpm;       // seconds per 8th

function musicSet(stateName, immediate) {
  if (!A.ok) return;
  if (A.state === stateName && !A.pending) return;
  if (!A.scores[stateName]) return;
  A.pending = stateName;
  if (immediate || !A.score) applyPending();
}
function applyPending() {
  if (!A.pending) return;
  const s = A.scores[A.pending];
  A.state = A.pending; A.pending = '';
  A.score = s; A.bpm = s.bpm; A.bar = 0; A.beat = 0; A.sect++;
  newSection(s);
  if (A.musicBus) {
    const t = A.ctx.currentTime;
    A.musicBus.gain.cancelScheduledValues(t);
    A.musicBus.gain.setValueAtTime(Math.max(.0001, A.musicBus.gain.value), t);
    A.musicBus.gain.linearRampToValueAtTime(A.muted ? 0 : A.volMusic, t + 1.6);
  }
}
function musicIntensity(v) { A.targetIntensity = sat(v); }

function musicStart() {
  if (!A.ok || A.timer) return;
  A.nextTime = A.ctx.currentTime + 0.12;
  if (!A.score) { A.pending = 'menu'; applyPending(); }
  A.timer = setInterval(schedTick, 32);
}
function musicStop() { if (A.timer) { clearInterval(A.timer); A.timer = null; } }

function schedTick() {
  if (!A.ok || !A.score) return;
  const c = A.ctx;
  if (c.state === 'suspended') return;
  const look = c.currentTime + 0.28;
  let guard = 0;
  while (A.nextTime < look && guard++ < 64) {
    scheduleEighth(A.nextTime);
    A.nextTime += S8();
    A.beat++;
    if (A.beat >= 8) {                       // one bar = 8 eighths (4/4)
      A.beat = 0; A.bar++;
      if (A.pending && A.bar % 2 === 0) applyPending();
      else if (A.bar % A.score.bars === 0) { A.sect++; if (Math.random() < .55) newSection(A.score); }
    }
  }
  A.intensity += (A.targetIntensity - A.intensity) * 0.06;
}

function scheduleEighth(t) {
  const s = A.score, L = s.lay, dst = A.musicBus;
  const barInProg = A.bar % s.prog.length;
  const deg = s.prog[barInProg];
  const mode = s.mode, root = s.root;
  const e = A.beat;                                   // 0..7
  const inten = clamp(s.base + A.intensity * (1 - s.base) * 1.15, 0, 1.12);
  const sw = (e % 2 === 1) ? S8() * (s.swing || 0) : 0;
  t += sw;
  const chord = chordNotes(mode, root, deg, s.sevenths, 0);
  const beatQ = e >> 1, isDown = e === 0, isBackbeat = (e === 4);

  /* ---- PAD: sustained chord at bar start ---- */
  if (L.pad && isDown) {
    const d = SPB() * 4 * .98;
    for (let i = 0; i < chord.length; i++)
      vPad(t, hz(chord[i] + 12), d, .05 * L.pad * (0.6 + inten * .5), dst);
  }
  /* ---- BASS ---- */
  if (L.bass) {
    const pat = s.bpm > 118 ? [1, 0, 1, 1, 0, 1, 1, 0] : [1, 0, 0, 1, 0, 0, 1, 0];
    if (pat[e]) {
      const bn = root + degToSemi(mode, deg) - 24 + (e >= 4 && s.bpm > 118 ? 0 : 0);
      vBass(t, hz(bn), S8() * (s.bpm > 118 ? .9 : 1.7), .19 * L.bass * (.7 + inten * .5), dst);
    }
  }
  /* ---- STRINGS: chord bed with rhythmic articulation ---- */
  if (L.strings && inten > .28) {
    if (s.bpm > 118) {
      if (e % 2 === 0) for (const n of chord) vStrings(t, hz(n + 12), S8() * 1.7, .034 * L.strings * inten, dst);
    } else if (isDown || isBackbeat) {
      for (const n of chord) vStrings(t, hz(n + 12), SPB() * 1.9, .03 * L.strings * (.5 + inten * .6), dst);
    }
  }
  /* ---- OSTINATO (combat/boss drive) ---- */
  if (L.ost && inten > .4) {
    const oi = [0, 4, 7, 4, 0, 7, 4, 7][e];
    vHarp(t, hz(root + degToSemi(mode, deg) + oi + 12), S8() * .9, .05 * L.ost * inten, dst);
  }
  /* ---- CHOIR: long tones every 2 bars ---- */
  if (L.choir && isDown && A.bar % 2 === 0 && inten > .2) {
    const d = SPB() * 7.6;
    vChoir(t, hz(chord[0] + 12), d, .028 * L.choir * (.6 + inten * .6), dst);
    vChoir(t, hz(chord[2] + 12), d, .022 * L.choir * (.6 + inten * .6), dst);
    if (s.sevenths && chord[3] != null) vChoir(t, hz(chord[3] + 12), d, .016 * L.choir * inten, dst);
  }
  /* ---- MELODY (motif) on harp / flute / brass depending on score ---- */
  if (A.motif) {
    const pos = (A.bar % 2) * 8 + e;
    for (const n of A.motif) {
      if (n.t !== pos) continue;
      const variant = Math.floor(A.bar / 2) % 4;
      const mn = transformMotif([n], A.motifRng || new RNG(1), variant)[0];
      const midi = root + degToSemi(mode, deg + mn.d) + 24;
      const dl = S8() * mn.l * .92;
      if (L.brass && inten > .55) vBrass(t, hz(midi - 12), dl, .05 * L.brass * inten, dst);
      if (L.flute) vFlute(t, hz(midi), dl, .05 * L.flute * (.5 + inten * .5), dst);
      if (L.harp) vHarp(t, hz(midi), dl, .06 * L.harp, dst);
      if (L.bell && !L.harp) vBell(t, hz(midi), dl, .045 * L.bell, dst);
    }
  }
  /* ---- HORN CALL: sparse, epic, on section starts ---- */
  if (L.horn && isDown && A.bar % 4 === 0 && inten > .3) {
    vHorn(t, hz(chord[0] + 12), SPB() * 3.4, .05 * L.horn * inten, dst);
    vHorn(t + SPB() * .5, hz(chord[2] + 12), SPB() * 2.8, .036 * L.horn * inten, dst);
  }
  /* ---- PERCUSSION ---- */
  if (L.drums && inten > .3) {
    const g = L.drums * (.4 + inten * .7);
    const kp = s.bpm > 118 ? [1, 0, 0, 1, 0, 0, 1, 0] : [1, 0, 0, 0, 1, 0, 0, 0];
    if (kp[e]) vKick(t, .5 * g, dst);
    if (isBackbeat && s.bpm > 100) vSnare(t, .16 * g, dst);
    if (e % 2 === 0 || inten > .7) vHat(t, .045 * g, dst, e === 6 && inten > .8);
  }
  if (L.taiko && inten > .45) {
    const tp = [1, 0, 0, 0, 1, 0, 1, 0];
    if (tp[e]) vTaiko(t, .34 * L.taiko * inten, dst);
    if (A.bar % 8 === 0 && isDown) vCymbal(t, .1 * L.taiko, dst);
  }
}

/* ------------------------------ SFX ------------------------------ */
function sfx(name, vol, pitch) {
  if (!A.ok || A.muted) return;
  const c = A.ctx; if (c.state === 'suspended') return;
  const now = c.currentTime;
  // rate-limit identical sfx so bursts don't clip
  const lk = A.lastSfx[name] || 0;
  if (now - lk < 0.035) return; A.lastSfx[name] = now;
  const t = now + 0.005, dst = A.sfxBus;
  const g0 = (vol == null ? 1 : vol), p = pitch == null ? 1 : pitch;
  switch (name) {
    case 'swing': {
      const n = noiseSrc(t), bp = c.createBiquadFilter(); bp.type = 'bandpass';
      bp.frequency.setValueAtTime(fq(900 * p), t); bp.frequency.exponentialRampToValueAtTime(fq(2600 * p), t + .1); bp.Q.value = 1.4;
      const g = c.createGain(); g.gain.setValueAtTime(.0001, t); g.gain.exponentialRampToValueAtTime(.22 * g0, t + .03);
      g.gain.exponentialRampToValueAtTime(.0001, t + .17);
      n.connect(bp); bp.connect(g); g.connect(dst); n.start(t); n.stop(t + .2); break;
    }
    case 'hit': {
      const o = osc('triangle', 220 * p, t); o.frequency.exponentialRampToValueAtTime(80 * p, t + .1);
      const g = c.createGain(); g.gain.setValueAtTime(.3 * g0, t); g.gain.exponentialRampToValueAtTime(.0001, t + .18);
      const n = noiseSrc(t), bp = c.createBiquadFilter(); bp.type = 'bandpass'; bp.frequency.value = fq(1800 * p); bp.Q.value = .9;
      const ng = c.createGain(); ng.gain.setValueAtTime(.2 * g0, t); ng.gain.exponentialRampToValueAtTime(.0001, t + .09);
      n.connect(bp); bp.connect(ng); ng.connect(dst); n.start(t); n.stop(t + .12);
      o.connect(g); g.connect(dst); o.start(t); o.stop(t + .2); sendRev(g, .16); break;
    }
    case 'crit': {
      for (let i = 0; i < 3; i++) {
        const o = osc('square', 520 * p * (1 + i * .5), t + i * .022);
        o.frequency.exponentialRampToValueAtTime(160 * p, t + .16 + i * .02);
        const g = c.createGain(); g.gain.setValueAtTime(.16 * g0, t + i * .022); g.gain.exponentialRampToValueAtTime(.0001, t + .3);
        o.connect(g); g.connect(dst); o.start(t + i * .022); o.stop(t + .32); sendRev(g, .3);
      }
      vSnare(t, .18 * g0, dst); break;
    }
    case 'block': {
      const o = osc('square', 1500 * p, t); o.frequency.exponentialRampToValueAtTime(700 * p, t + .07);
      const g = c.createGain(); g.gain.setValueAtTime(.14 * g0, t); g.gain.exponentialRampToValueAtTime(.0001, t + .2);
      o.connect(g); g.connect(dst); o.start(t); o.stop(t + .22); sendRev(g, .4); break;
    }
    case 'cast': {
      const o = osc('sine', 300 * p, t); o.frequency.exponentialRampToValueAtTime(1200 * p, t + .35);
      const o2 = osc('sine', 450 * p, t); o2.frequency.exponentialRampToValueAtTime(1800 * p, t + .35);
      const g = c.createGain(); g.gain.setValueAtTime(.0001, t); g.gain.exponentialRampToValueAtTime(.11 * g0, t + .2);
      g.gain.exponentialRampToValueAtTime(.0001, t + .45);
      o.connect(g); o2.connect(g); g.connect(dst); o.start(t); o2.start(t); o.stop(t + .46); o2.stop(t + .46); sendRev(g, .5); break;
    }
    case 'fire': {
      const n = noiseSrc(t), lp = c.createBiquadFilter(); lp.type = 'lowpass';
      lp.frequency.setValueAtTime(fq(2600 * p), t); lp.frequency.exponentialRampToValueAtTime(300, t + .5);
      const g = c.createGain(); g.gain.setValueAtTime(.3 * g0, t); g.gain.exponentialRampToValueAtTime(.0001, t + .55);
      n.connect(lp); lp.connect(g); g.connect(dst); n.start(t); n.stop(t + .58);
      const o = osc('sawtooth', 110 * p, t); o.frequency.exponentialRampToValueAtTime(40, t + .4);
      const g2 = c.createGain(); g2.gain.setValueAtTime(.18 * g0, t); g2.gain.exponentialRampToValueAtTime(.0001, t + .45);
      o.connect(g2); g2.connect(dst); o.start(t); o.stop(t + .48); sendRev(g, .35); break;
    }
    case 'ice': {
      for (let i = 0; i < 5; i++) vBell(t + i * .03, 900 * p * (1 + i * .28), .18, .05 * g0, dst);
      break;
    }
    case 'heal': {
      const notes = [0, 4, 7, 12];
      for (let i = 0; i < notes.length; i++) vBell(t + i * .05, hz(72 + notes[i]) * p, .5, .07 * g0, dst);
      break;
    }
    case 'levelup': {
      const notes = [0, 4, 7, 12, 16, 19];
      for (let i = 0; i < notes.length; i++) {
        vBell(t + i * .07, hz(69 + notes[i]), .9, .1 * g0, dst);
        vBrass(t + i * .07, hz(57 + notes[i]), .5, .07 * g0, dst);
      }
      vCymbal(t, .12 * g0, dst); break;
    }
    case 'loot': {
      const set = [[0, 5], [0, 7], [0, 7, 12], [0, 7, 12, 16], [0, 7, 12, 16, 19], [0, 7, 12, 19, 24]][clamp(Math.round(p) - 1, 0, 5)] || [0, 7];
      for (let i = 0; i < set.length; i++) vBell(t + i * .06, hz(76 + set[i]), .7, .09 * g0, dst);
      break;
    }
    case 'coin': {
      vBell(t, 2100, .12, .07 * g0, dst); vBell(t + .05, 2800, .16, .05 * g0, dst); break;
    }
    case 'quest': {
      const notes = [0, 7, 12];
      for (let i = 0; i < 3; i++) { vHarp(t + i * .08, hz(72 + notes[i]), .5, .1 * g0, dst); }
      break;
    }
    case 'questdone': {
      const notes = [0, 4, 7, 12];
      for (let i = 0; i < 4; i++) { vHorn(t + i * .09, hz(60 + notes[i]), .7, .07 * g0, dst); vBell(t + i * .09, hz(84 + notes[i]), .6, .05 * g0, dst); }
      break;
    }
    case 'death': {
      const o = osc('sawtooth', 220, t); o.frequency.exponentialRampToValueAtTime(45, t + 1.1);
      const lp = c.createBiquadFilter(); lp.type = 'lowpass'; lp.frequency.setValueAtTime(1400, t); lp.frequency.exponentialRampToValueAtTime(180, t + 1.1);
      const g = c.createGain(); g.gain.setValueAtTime(.24 * g0, t); g.gain.exponentialRampToValueAtTime(.0001, t + 1.3);
      o.connect(lp); lp.connect(g); g.connect(dst); o.start(t); o.stop(t + 1.35); sendRev(g, .7); break;
    }
    case 'roar': {
      const o = osc('sawtooth', 70, t); o.frequency.setValueAtTime(70, t);
      o.frequency.linearRampToValueAtTime(130, t + .35); o.frequency.exponentialRampToValueAtTime(48, t + 1.4);
      const lp = c.createBiquadFilter(); lp.type = 'lowpass'; lp.frequency.value = 900; lp.Q.value = 4;
      const g = c.createGain(); g.gain.setValueAtTime(.0001, t); g.gain.exponentialRampToValueAtTime(.34 * g0, t + .18);
      g.gain.exponentialRampToValueAtTime(.0001, t + 1.5);
      const n = noiseSrc(t), nb = c.createBiquadFilter(); nb.type = 'bandpass'; nb.frequency.value = 420; nb.Q.value = .6;
      const ng = c.createGain(); ng.gain.setValueAtTime(.16 * g0, t); ng.gain.exponentialRampToValueAtTime(.0001, t + 1.2);
      n.connect(nb); nb.connect(ng); ng.connect(dst); n.start(t); n.stop(t + 1.25);
      o.connect(lp); lp.connect(g); g.connect(dst); o.start(t); o.stop(t + 1.55); sendRev(g, .85); break;
    }
    case 'step': {
      const n = noiseSrc(t), lp = c.createBiquadFilter(); lp.type = 'lowpass'; lp.frequency.value = fq(620 * p); lp.Q.value = .6;
      const g = c.createGain(); g.gain.setValueAtTime(.075 * g0, t); g.gain.exponentialRampToValueAtTime(.0001, t + .09);
      n.connect(lp); lp.connect(g); g.connect(dst); n.start(t); n.stop(t + .1); break;
    }
    case 'jump': {
      const o = osc('sine', 320, t); o.frequency.exponentialRampToValueAtTime(620, t + .13);
      const g = c.createGain(); g.gain.setValueAtTime(.09 * g0, t); g.gain.exponentialRampToValueAtTime(.0001, t + .16);
      o.connect(g); g.connect(dst); o.start(t); o.stop(t + .18); break;
    }
    case 'land': {
      const n = noiseSrc(t), lp = c.createBiquadFilter(); lp.type = 'lowpass'; lp.frequency.value = 420;
      const g = c.createGain(); g.gain.setValueAtTime(.14 * g0, t); g.gain.exponentialRampToValueAtTime(.0001, t + .15);
      n.connect(lp); lp.connect(g); g.connect(dst); n.start(t); n.stop(t + .17); break;
    }
    case 'ui': {
      const o = osc('square', 900 * p, t); const g = c.createGain();
      g.gain.setValueAtTime(.05 * g0, t); g.gain.exponentialRampToValueAtTime(.0001, t + .06);
      o.connect(g); g.connect(dst); o.start(t); o.stop(t + .07); break;
    }
    case 'open': {
      vHarp(t, 520, .3, .07 * g0, dst); vHarp(t + .04, 780, .35, .05 * g0, dst); break;
    }
    case 'portal': {
      const o = osc('sine', 120, t); o.frequency.exponentialRampToValueAtTime(900, t + .9);
      const n = noiseSrc(t), bp = c.createBiquadFilter(); bp.type = 'bandpass'; bp.frequency.setValueAtTime(300, t);
      bp.frequency.exponentialRampToValueAtTime(fq(4000), t + .9); bp.Q.value = 3;
      const g = c.createGain(); g.gain.setValueAtTime(.0001, t); g.gain.exponentialRampToValueAtTime(.16 * g0, t + .5);
      g.gain.exponentialRampToValueAtTime(.0001, t + 1.1);
      o.connect(g); n.connect(bp); bp.connect(g); g.connect(dst);
      o.start(t); n.start(t); o.stop(t + 1.15); n.stop(t + 1.15); sendRev(g, .7); break;
    }
    case 'error': {
      const o = osc('square', 200, t); o.frequency.setValueAtTime(150, t + .08);
      const g = c.createGain(); g.gain.setValueAtTime(.07 * g0, t); g.gain.exponentialRampToValueAtTime(.0001, t + .18);
      o.connect(g); g.connect(dst); o.start(t); o.stop(t + .2); break;
    }
  }
}
